version: '3.8'
services:
  products-warehouse-api-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-service/products_warehouse_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
    depends_on:
      - postgres-service

  postgres-service:
    image: postgres:14.1
    container_name: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: "products_warehouse_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"